package persistence;

import datarecords.*;

import javax.sql.DataSource;
import java.net.PasswordAuthentication;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Class that executes as well as prepares the actual SQL Commands
 */
public class DatabaseManagerImpl implements DatabaseManager {

        private final DataSource ds = DBProvider.getDataSource("aisdb.jdbc");
        private Connection con ;


    //================================================================================================================//
    /* Primary-Methods                                                                                                 */
    //================================================================================================================//

    /**
     * Execute a prepared select statement
     *
     * @param statement The statement generated by one of the prepare-Helper-Methods
     * @return a result set
     */
    @Override
    public ResultSet executeSQLSelect(PreparedStatement statement) {
        try {

            return statement.executeQuery();

        } catch (Exception e) {

            e.printStackTrace();
            return null;
        }
    }

    /**
     * Execute a prepared insert statement. Method automatically identifies type of data and creates as well as executes  a SQL statement
     *
     * @param t the data that is about to be inserted
     * @return whether the Prepared Statement could successfully be executed
     */
        @Override
        public <T> boolean executeSQLInsert(T t) {

            PreparedStatement statement;
            if (t.getClass() == AirportData.class){
                statement = prepareAirportInsert(t);
            }else if(t.getClass() == PlaneData.class){
                statement = preparePlaneInsert(t);
            }else if(t.getClass() == PlaneModelData.class){
                statement = preparePlaneModelInsert(t);
            }else if(t.getClass() == AccountData.class){
                statement = prepareAccountInsert(t);
            }else if (t.getClass() == FlightData.class){
                statement = prepareFlightInsert(t);
            } else if(t.getClass() == RouteData.class){
                statement = prepareRouteInsert(t);
            }else {

                return false;
            }
            try {
                assert statement != null;
                statement.execute();
                statement.close();
                return true;

            } catch (Exception e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());
                return false;
            }
        }

    //================================================================================================================//
    /* Helper-Methods                                                                                                 */
    //================================================================================================================//


    public Connection connect()  {

        try {
            return ds.getConnection("aisdemouser", "ais");
        } catch (SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        return null;
    }

    /**
     * Create the Prepared Statement to Insert a AirportDataObject into the airports table.
     *
     * @param t airport data
     * @return whether the preparation of the Statement
     *         and establishing the DB Connection has been successful.
     */
    @Override
    public <T> PreparedStatement prepareAirportInsert(T t) {

        assert t.getClass() == AirportData.class;
        AirportData airportData = (AirportData) t;


        String sql = " INSERT INTO aisdb.ais.airports VALUES (?, ?, ?, ?, ?, ?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, airportData.getAbbreviation());
            statement.setDouble(2, airportData.getCoordinateData().getLatitude());
            statement.setDouble(3, airportData.getCoordinateData().getLongitude());
            statement.setString(4, airportData.getAirportName());
            statement.setString(5, airportData.getCountryName());
            statement.setString(6, airportData.getCityName());
            statement.setString(7, airportData.getZone());

            return statement;

        } catch (SQLException e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());

                return null;
        }
    }


    /**
     * Create the Prepared  Statement to Insert a PlaneData Object into the planes table.
     *
     * @param t plane data
     * @return  whether the connection to the database and the prepared statement
     *          could be successfully established
     */
    @Override

    public <T> PreparedStatement preparePlaneInsert(T t){

        assert t.getClass() == PlaneData.class;
        PlaneData planeData = (PlaneData) t;

        String sql = " INSERT INTO aisdb.ais.planes (\"plane-model\", economyclass, businessclass, firstclass) VALUES (?, ?, ?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);

            //get plane model number from database!
            statement.setInt(1, getPlaneModelID(planeData.getPlaneModelData()));
            statement.setInt(2, planeData.getEconomySeats());
            statement.setInt(3, planeData.getBusinessSeats());
            statement.setInt(4, planeData.getFirstClassSeats());
            return statement;

        } catch (Exception e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

            return null;
        }
    }


    /**
     * Create the Prepared Statement to insert a AccountDataObject into the accounts table
     *
     * @param t Account data
     * @return whether the connection to the database and the prepared statement
     *         could be successfully established
     */
    @Override
        public <T> PreparedStatement prepareAccountInsert(T t){

            assert t.getClass() == AccountData.class;
            AccountData accountData = (AccountData) t;
            String sql = " INSERT INTO aisdb.ais.accounts (firstname, lastname, position, salt, \"e-Mail\", password) VALUES(?, ?, ?, ?, ?, ?) ";

            try {
                con = connect();

                PreparedStatement statement = con.prepareStatement(sql);
                statement.setString(1, accountData.getFirstname());
                statement.setString(2,accountData.getLastname());
                statement.setString(3, accountData.getPosition());
                statement.setString(4, accountData.getSalt());
                statement.setString(5, accountData.geteMail());
                statement.setString(6, accountData.getPasswordHash());

                return statement;

            }catch (Exception e){

                System.err.println(e.getClass().getName() + ": " + e.getMessage());
                return null;

            }
        }

    @Override
    public <T> PreparedStatement preparePlaneModelInsert(T t){

        assert t.getClass() == PlaneModelData.class;
        PlaneModelData planeModelData = (PlaneModelData) t;

        String sql = " INSERT INTO aisdb.ais.\"planeModels\" (\"model-number\", manufacturer, seats, \"range\", speed, \"weight-capacity\") VALUES (?, ?, ?, ?, ?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, planeModelData.getModelNumber());
            statement.setString(2, planeModelData.getManufacturer());
            statement.setInt(3, planeModelData.getSeats());
            statement.setDouble(4, planeModelData.getRange());
            statement.setInt(5, planeModelData.getSpeed());
            statement.setDouble(6, planeModelData.getWeightCapacity());

            return statement;

        }catch (Exception e){

            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            return null;

        }
    }


    @Override
    public <T> PreparedStatement prepareRouteInsert(T t) {

        assert t.getClass() == RouteData.class;
        String sql = "INSERT INTO aisdb.ais.routes (origin, destination) VALUES (?, ?)";
        RouteData data = (RouteData) t;

        try {

            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, data.getOrigin().getAbbreviation());
            statement.setString(2, data.getDestination().getAbbreviation());
            System.out.println(statement);
            return statement;
        }catch (SQLException e){
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        return null;
    }

    @Override
    public <T> PreparedStatement prepareFlightInsert(T t) {
        assert t.getClass() == FlightData.class;
        FlightData flightData = (FlightData) t;

        String sql = " INSERT INTO aisdb.ais.flights (\"flight-date\", \"flight-route-id\", \"flight-plane\", price, duration) VALUES(?, ?, ?, ?, ?) ";

        try {
            con = connect();
            PreparedStatement statement = con.prepareStatement(sql);

            Timestamp timestamp = Timestamp.valueOf(flightData.getDeparture());
            statement.setTimestamp(1, timestamp);
            statement.setInt(2, getRouteID(flightData.getRoute()));
            statement.setInt(3, getPlaneID(flightData.getPlane()));
            statement.setFloat(4, flightData.getPrice());
            statement.setInt(5, flightData.getDuration());

            return statement;

        }catch (Exception e){
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            return null;
        }
    }

    @Override
        public PasswordAuthentication getAccountData(String string){

            String sql = "SELECT \"e-Mail\", password FROM aisdb.ais.accounts WHERE \"e-Mail\"=?";

            String user = null;
            String pw = null;

            try {
                con = connect();

                PreparedStatement statement = con.prepareStatement(sql);
                statement.setString(1, string);

                ResultSet rs = statement.executeQuery();

                if (rs.next()){
                    user = rs.getString(1);
                    pw = rs.getString(2);
                }


            } catch (SQLException e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());

            }

            if (user == null || pw == null) {
                return null;
            }
            return new PasswordAuthentication(user,pw.toCharArray());


        }

    @Override
    public List<PlaneModelData> getAllPlaneModels() {

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement("SELECT * FROM aisdb.ais.\"planeModels\"");
            ResultSet rs = statement.executeQuery();
            List<PlaneModelData> planeModelList = new ArrayList<>();
            while(rs.next()){
                String manufacturer = rs.getString("manufacturer");
                String modelnumber = rs.getString("model-number");
                int seats = rs.getInt("seats");
                double range = rs.getDouble("range");
                int speed = rs.getInt("speed");
                double weightCapacity = rs.getDouble("weight-capacity");

                planeModelList.add(new PlaneModelData(manufacturer, modelnumber, seats, range, weightCapacity, speed));

            }
            rs.close();
            statement.close();
            return planeModelList;

        } catch (SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        return null;
    }


    @Override
    public String getSalt(String string){

        String returner = null;
        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement("SELECT salt FROM aisdb.ais.accounts WHERE \"e-Mail\" = ?");
            statement.setString(1, string);


            ResultSet rs = statement.executeQuery();

            while(rs.next()){
                returner = rs.getString("salt");
            }
            rs.close();
            statement.close();
            return returner;


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());


        }

        return "Couldn't fetch Salt";
    }

    @Override
    public String getPosition(String str) {

        String sql = "SELECT position FROM aisdb.ais.accounts WHERE \"e-Mail\"=?";

        String position = null;

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, str);

            ResultSet rs = statement.executeQuery();

            if (rs.next()){
                position = rs.getString(1);
            }


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

        }

        return position;
    }


    public int getPlaneModelID(PlaneModelData planeModelData){
        String ID = null;
        String sql = "SELECT \"model-ID\" FROM aisdb.ais.\"planeModels\" WHERE manufacturer= ? AND \"model-number\"= ?";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);

            statement.setString(1, planeModelData.getManufacturer());
            statement.setString(2,planeModelData.getModelNumber());

            ResultSet rs = statement.executeQuery();

            if (rs.next()){
                ID = rs.getString(1);
            }


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

        }

        // it needs to be added that if the number 99999 (5x9) no plane could be found
        if (ID == null ){
            return 99999;
        }

        return Integer.parseInt(ID);
    }

    public int getRouteID(RouteData routeData){
        String ID = null;
        String sql = "SELECT id FROM aisdb.ais.routes WHERE origin= ? AND destination= ?";

        try {
            con = connect();
            PreparedStatement statement = con.prepareStatement(sql);

            statement.setString(1, routeData.getOrigin().getAbbreviation());
            statement.setString(2, routeData.getDestination().getAbbreviation());

            ResultSet rs = statement.executeQuery();

            if (rs.next()){
                ID = rs.getString(1);
            }

        } catch (SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        // it needs to be added that if the number 99999 (5x9) no plane could be found ( maybe even method checkID(ID) that returns the value whatever ID is )
        if (ID == null ){
            return 99999;
        }

        return Integer.parseInt(ID);
    }

    public int getPlaneID(PlaneData planeData){
        String ID = null;
        String sql = "SELECT \"plane-number\" FROM aisdb.ais.planes WHERE \"plane-model\"= ? AND economyclass= ? AND businessclass= ? AND firstclass= ?";

        try {
            con = connect();
            PreparedStatement statement = con.prepareStatement(sql);

            statement.setInt(1, getPlaneModelID(planeData.getPlaneModelData()));
            statement.setInt(2, planeData.getEconomySeats());
            statement.setInt(3, planeData.getBusinessSeats());
            statement.setInt(4, planeData.getFirstClassSeats());

            ResultSet rs = statement.executeQuery();

            if (rs.next()){
                ID = rs.getString(1);
            }

        } catch (SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        // it needs to be added that if the number 99999 (5x9) no plane could be found
        if (ID == null ){
            return 99999;
        }

        return Integer.parseInt(ID);
    }


    @Override
    public ArrayList<AirportData> getAllAirports() {
        String sql = "SELECT \"airport-name\", abbreviation, country, \"Latitude\", \"Longitude\", city, \"timezone\"  FROM aisdb.ais.airports";

        ArrayList<AirportData> list = new ArrayList<>();
        int i = 0;

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();

            while (rs.next()){
                AirportData data = new AirportData(rs.getString("airport-name"),
                        rs.getString("abbreviation"),
                        rs.getString("country"),
                        new CoordinateData(rs.getDouble("Latitude"), rs.getDouble("Longitude") ),
                        rs.getString("city"),
                        rs.getString("timezone"));
                list.add(i,data);
                i++;
            }
        } catch (SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        return list;
    }

    @Override
    public ArrayList<String> getAirports() {

        String sql = "SELECT \"airport-name\",city FROM aisdb.ais.airports";

        ArrayList<String> list = new ArrayList<>();
        int i = 0;
        try {

            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);

            ResultSet rs = statement.executeQuery();

            while (rs.next()){

                String stringHelper= rs.getString("airport-name") + ", " + rs.getString("city");
                list.add(i,stringHelper);
                i++;

            }


        }catch (SQLException e){
            System.err.println(e.getClass().getName() + ": " + e.getMessage() + " : in DatabaseManager.getAirports");
        }

        if (list.isEmpty()){
            list.add("Couldn't fetch Airports!");
        }

        return list;
    }

    @Override
    public AirportData getAirport(String str) {
        String sql = "SELECT * FROM aisdb.ais.airports WHERE \"airport-name\"=?";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1,str);

            ResultSet rs = statement.executeQuery();

            if(rs.next()){

                return new AirportData(rs.getString("airport-name"),rs.getString("abbreviation"),rs.getString("country"),new CoordinateData(rs.getDouble("latitude"), rs.getDouble("longitude") ),rs.getString("city"), rs.getString("timezone"));

            }
        }catch (SQLException e){
            System.err.println(e.getClass().getName() + ": " + e.getMessage() + " : in DatabaseManager.getAirport");
        }

        return null;
    }

    @Override
    public String checkZone(double d) {

        String sql = "SELECT abbreviation FROM aisdb.ais.timezones WHERE \"startLong\"<=? AND \"endLong\">=? OR \"startLong\">=? AND \"endLong\"<=?";

        String Zone = null;

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setDouble(1, d);
            statement.setDouble(2, d);
            statement.setDouble(3, d);
            statement.setDouble(4, d);

            ResultSet rs = statement.executeQuery();

            if (rs.next()){
                Zone = rs.getString(1);
            }


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

        }

        return Zone;
    }

    @Override
    public ArrayList<String> getAllRoutes() {

        String sql = "";

        ArrayList<String> list = new ArrayList<>();
        int i = 0;
        int j=0;
        try {

            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);

            ResultSet rs = statement.executeQuery();

            while (rs.next()){
                String stringHelper= rs.getString(i+1) + ", " + rs.getString(i+2);
                list.add(j,stringHelper);
                i+=2;
                j++;
            }


        }catch (SQLException e){
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        if (list.isEmpty()){
            list.add("Couldn't fetch Airports!");
        }

        return list;
    }

}
