package persistence;

import datarecords.AccountData;
import datarecords.AirportData;
import datarecords.PlaneData;
import datarecords.PlaneModelData;

import javax.sql.DataSource;
import java.net.PasswordAuthentication;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Class that executes as well as prepares the actual SQL Commands
 */
public class DatabaseManagerImpl implements DatabaseManager {

        private final DataSource ds = DBProvider.getDataSource("aisdb.jdbc");
        private Connection con ;


    //================================================================================================================//
    /* Primary-Methods                                                                                                 */
    //================================================================================================================//

    /**
     * Execute a prepared select statement
     *
     * @param statement The statement generated by one of the prepare-Helper-Methods
     * @return a resultset
     * @throws Exception
     */
    @Override
    public ResultSet executeSQLSelect(PreparedStatement statement) throws Exception {
        try {

            return statement.executeQuery();

        } catch (Exception e) {

            e.printStackTrace();
            return null;
        }
    }

    /**
     * Execute a prepared insert statement
     *
     * @param statement The statement generated by one of the prepare-Helper-Methods
     * @return whether the Prepared Statement could successfully be executed
     * @throws Exception
     */
        @Override
        public boolean executeSQLInsert(PreparedStatement statement) throws Exception {

            try {

                statement.execute();
                statement.close();
                return true;

            } catch (Exception e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());
                return false;
            }
        }

    //================================================================================================================//
    /* Helper-Methods                                                                                                 */
    //================================================================================================================//


    public Connection connect()  {

        try {
            return ds.getConnection("aisdemouser", "ais");
        } catch (SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        return null;
    }

    /**
     * Create the Prepared Statement to Insert a AirportDataObject into the airports table.
     *
     * @param airportData
     * @return whether the preparation of the Statement
     *         and establishing the DB Connection has been successful.
     * @throws Exception
     */
    @Override
    public PreparedStatement prepareAirportInsert(AirportData airportData) {

        String sql = " INSERT INTO aisdb.ais.airports VALUES (?, ?, ?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1,airportData.getAbbreviation());
            statement.setDouble(2, airportData.getCoordinateData().getLatitude());
            statement.setDouble(3, airportData.getCoordinateData().getLongitude());
            statement.setString(4,airportData.getAirportName());

            return statement;

        } catch (Exception e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());

                return null;
        }
    }


    /**
     * Create the Prepared  Statement to Insert a PlaneData Object into the planes table.
     *
     * @param planeData
     * @return  whether the connection to the database and the prepared statement
     *          could be successfully established
     */
    @Override
    public PreparedStatement preparePlaneInsert(PlaneData planeData){
        String sql = " INSERT INTO aisdb.ais.planes (\"plane-model\", economyclass, businessclass, firstclass) VALUES (?, ?, ?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);

            //get plane model number from database!
            statement.setInt(1, getPlaneModelID(planeData.getPlaneModelData()));
            statement.setInt(2, planeData.getEconomySeats());
            statement.setInt(3, planeData.getBusinessSeats());
            statement.setInt(4, planeData.getFirstClassSeats());
            return statement;

        } catch (Exception e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

            return null;
        }
    }


    /**
     * Create the Prepared Statement to insert a AccountDataObject into the accounts table
     *
     * @param accountData
     * @return whether the connection to the database and the prepared statement
     *         could be successfully established
     */
    @Override
        public PreparedStatement prepareAccountInsert(AccountData accountData){
            String sql = " INSERT INTO aisdb.ais.accounts VALUES(?, ?, ?, ?, ?, ?) ";

            try {
                con = connect();

                PreparedStatement statement = con.prepareStatement(sql);
                statement.setString(1, accountData.getFirstname());
                statement.setString(2,accountData.getLastname());
                statement.setString(3, accountData.getPosition());
                statement.setString(4, accountData.getSalt());
                statement.setString(5, accountData.geteMail());
                statement.setString(6, accountData.getPasswordHash());

                return statement;

            }catch (Exception e){

                System.err.println(e.getClass().getName() + ": " + e.getMessage());
                return null;

            }
        }

    @Override
    public PreparedStatement preparePlaneModelInsert(PlaneModelData planeModelData){
        String sql = " INSERT INTO aisdb.ais.\"planeModels\" VALUES(?, ?, ?, ?, ?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, planeModelData.getModelNumber());
            statement.setString(2, planeModelData.getManufacturer());
            statement.setInt(3, planeModelData.getSeats());
            statement.setDouble(4, planeModelData.getRange());
            statement.setInt(5, planeModelData.getSpeed());
            statement.setDouble(6, planeModelData.getWeightCapacity());

            return statement;

        }catch (Exception e){

            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            return null;

        }
    }

        @Override
        public PasswordAuthentication getAccountData(String string){

            String sql = "SELECT \"e-Mail\", password FROM aisdb.ais.accounts WHERE \"e-Mail\"=?";

            String user = null;
            String pw = null;

            try {
                con = connect();

                PreparedStatement statement = con.prepareStatement(sql);
                statement.setString(1, string);

                ResultSet rs = statement.executeQuery();

                if (rs.next()){
                    user = rs.getString(1);
                    pw = rs.getString(2);
                }


            } catch (SQLException e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());

            }

            assert pw != null;
            return new PasswordAuthentication(user,pw.toCharArray());


        }


    @Override
    public String getSalt(String string){

        String returner = null;
        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement("SELECT salt FROM aisdb.ais.accounts WHERE \"e-Mail\" = ?");
            statement.setString(1, string);


            ResultSet rs = statement.executeQuery();

            while(rs.next()){
                returner = rs.getString("salt");
            }
            rs.close();
            statement.close();
            return returner;


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());


        }

        return "Couldn't fetch Salt";
    }

    @Override
    public String getPosition(String str) {

        String sql = "SELECT position FROM aisdb.ais.accounts WHERE \"e-Mail\"=?";

        String position = null;

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, str);

            ResultSet rs = statement.executeQuery();

            if (rs.next()){
                position = rs.getString(1);
            }


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

        }

        return position;
    }


    public int getPlaneModelID(PlaneModelData planeModelData){
        String ID = null;
        String sql = "SELECT \"model-ID\" FROM aisdb.ais.\"planeModels\" WHERE manufacturer= ? AND \"model-number\"= ?";



        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);

            statement.setString(1, planeModelData.getManufacturer());
            statement.setString(2,planeModelData.getModelNumber());

            ResultSet rs = statement.executeQuery();

            if (rs.next()){
                ID = rs.getString(1);
            }


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

        }
        return Integer.parseInt(ID);
    }
}

