package persistence;

import datarecords.*;

import javax.sql.DataSource;
import java.net.PasswordAuthentication;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Class that executes as well as prepares SQL Statements.
 * Used within the StorageService
 */
public class DatabaseManagerImpl implements DatabaseManager {

        private final DataSource ds = DBProvider.getDataSource("aisdb.jdbc");
        private Connection con ;


    //================================================================================================================//
    /* Primary-Methods                                                                                                 */
    //================================================================================================================//

    /**
     * Execute a prepared select statement
     *
     * @param statement The statement generated by one of the prepare-Helper-Methods
     * @return a resultset
     * @throws Exception
     */
    @Override
    public ResultSet executeSQLSelect(PreparedStatement statement) throws Exception {
        try {

            return statement.executeQuery();

        } catch (Exception e) {

            e.printStackTrace();
            return null;
        }
    }

    /**
     * Execute a prepared insert statement. Parameter takes data and determines the type and prepares Statement based on that. If data type cannot
     * be identified, it returns false.
     *
     * @param t The data that is going to be inserted. A.e. AirportData, PlaneData, etc.
     * @return whether the Prepared Statement could successfully be executed
     */
    @Override
    public <T> boolean executeSQLInsert(T t) {

        PreparedStatement statement = null;
        if (t.getClass() == AirportData.class){
            statement = prepareAirportInsert(t);
        }else if(t.getClass() == PlaneData.class){
           statement = preparePlaneInsert(t);
        }else if(t.getClass() == PlaneModelData.class){
           statement = preparePlaneModelInsert(t);
        }else if(t.getClass() == AccountData.class){
           statement = prepareAccountInsert(t);
        }else return false;
        try {
            assert statement != null;
            statement.execute();
            statement.close();
            return true;
        } catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            return false;
        }
    }

    //================================================================================================================//
    /* Helper-Methods                                                                                                 */
    //================================================================================================================//


    public Connection connect()  {

        try {
            return ds.getConnection("aisdemouser", "ais");
        } catch (SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }

        return null;
    }

    /**
     * Create the Prepared Statement to Insert a AirportDataObject into the airports table.
     *
     * @param t
     * @return whether the preparation of the Statement
     *         and establishing the DB Connection has been successful.
     * @throws Exception
     */
    @Override
    public <T> PreparedStatement prepareAirportInsert(T t) {

        assert t.getClass() == AirportData.class;
        AirportData airportData = (AirportData) t;

        String sql = " INSERT INTO aisdb.ais.airports VALUES (?, ?, ?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1,airportData.getAbbreviation());
            statement.setDouble(2, airportData.getCoordinateData().getLatitude());
            statement.setDouble(3, airportData.getCoordinateData().getLongitude());
            statement.setString(4,airportData.getAirportName());

            return statement;

        } catch (Exception e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());

                return null;
        }
    }


    /**
     * Create the Prepared  Statement to Insert a PlaneData Object into the planes table.
     *
     * @param t
     * @return  whether the connection to the database and the prepared statement
     *          could be successfully established
     */
    @Override
    public <T> PreparedStatement preparePlaneInsert(T t){

        assert t.getClass() == PlaneData.class;
        PlaneData planeData = (PlaneData) t;

        String sql = " INSERT INTO aisdb.ais.planes VALUES (?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1,planeData.getPlaneNumber());
            statement.setString(2, planeData.getPlaneModelData().getModelNumber());
            return statement;

        } catch (Exception e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

            return null;
        }
    }


    /**
     * Create the Prepared Statement to insert a AccountDataObject into the accounts table
     *
     * @param t
     * @return whether the connection to the database and the prepared statement
     *         could be successfully established
     */
    @Override
        public <T> PreparedStatement prepareAccountInsert(T t){

            assert t.getClass() == AccountData.class;
            AccountData accountData = (AccountData) t;
            String sql = " INSERT INTO aisdb.ais.accounts VALUES(?, ?, ?, ?, ?, ?) ";

            try {
                con = connect();

                PreparedStatement statement = con.prepareStatement(sql);
                statement.setString(1, accountData.getFirstname());
                statement.setString(2,accountData.getLastname());
                statement.setString(3, accountData.getPosition());
                statement.setString(4, accountData.getSalt());
                statement.setString(5, accountData.geteMail());
                statement.setString(6, accountData.getPasswordHash());

                return statement;

            }catch (Exception e){

                System.err.println(e.getClass().getName() + ": " + e.getMessage());
                return null;

            }
        }

    @Override
    public <T> PreparedStatement preparePlaneModelInsert(T t){

        assert t.getClass() == PlaneModelData.class;
        PlaneModelData planeModelData = (PlaneModelData) t;

        String sql = " INSERT INTO aisdb.ais.\"planeModels\" VALUES(?, ?, ?, ?, ?, ?) ";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, planeModelData.getModelNumber());
            statement.setString(2, planeModelData.getManufacturer());
            statement.setInt(3, planeModelData.getSeats());
            statement.setDouble(4, planeModelData.getRange());
            statement.setInt(5, planeModelData.getSpeed());
            statement.setDouble(6, planeModelData.getWeightCapacity());

            return statement;

        }catch (Exception e){

            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            return null;

        }
    }


    @Override
    public <T> PreparedStatement prepareRouteInsert(T t) {

        assert t.getClass() == RouteData.class;
        RouteData routeData = (RouteData) t;

        String sql = "INSERT INTO aisdb.ais.routes VALUES(?,?)";

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, routeData.getOrigin().getAbbreviation());
            statement.setString(2, routeData.getDestination().getAbbreviation());

            return statement;

        }catch (SQLException e){
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }
        return null;
    }

    @Override
        public PasswordAuthentication getAccountData(String string){

            String sql = "SELECT \"e-Mail\", password FROM aisdb.ais.accounts WHERE \"e-Mail\"=?";

            String user = null;
            String pw = null;

            try {
                con = connect();

                PreparedStatement statement = con.prepareStatement(sql);
                statement.setString(1, string);

                ResultSet rs = statement.executeQuery();

                if (rs.next()){
                    user = rs.getString(1);
                    pw = rs.getString(2);
                }


            } catch (SQLException e) {

                System.err.println(e.getClass().getName() + ": " + e.getMessage());

            }

            assert pw != null;
            return new PasswordAuthentication(user,pw.toCharArray());


        }


    @Override
    public String getSalt(String string){

        String returner = null;
        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement("SELECT salt FROM aisdb.ais.accounts WHERE \"e-Mail\" = ?");
            statement.setString(1, string);


            ResultSet rs = statement.executeQuery();

            while(rs.next()){
                returner = rs.getString("salt");
            }
            rs.close();
            statement.close();
            return returner;


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());


        }

        return "Couldn't fetch Salt";
    }

    @Override
    public String getPosition(String str) {

        String sql = "SELECT position FROM aisdb.ais.accounts WHERE \"e-Mail\"=?";

        String position = null;

        try {
            con = connect();

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, str);

            ResultSet rs = statement.executeQuery();

            if (rs.next()){
                position = rs.getString(1);
            }


        } catch (SQLException e) {

            System.err.println(e.getClass().getName() + ": " + e.getMessage());

        }

        return position;
    }
}

