package persistence;

import datarecords.AirportData;
import datarecords.FlightData;
import datarecords.PlaneData;
import datarecords.RouteData;

import java.util.List;

/**
 * This class knows everything about storing and retrieving data from
 * the database. At the moment only returns dummy object with an id that is set.
 * Normally it will connect to a database and do all the handling.
 *
 * @author Jannick Gruschka
 */
public class StorageServiceImpl implements StorageService{
    @Override
    public AirportData add(AirportData airportData) {

        // Create dummy Data object with id. Normally, the id would be generated by the database
        return new AirportData( 1, airportData.getAirportName(), airportData.getAbbreviation(), airportData.getCityName(), airportData.getCountryName());

    }

    @Override
    public PlaneData add(PlaneData planeData) {

        // Create dummy Data object.
        return new PlaneData(planeData.getPlaneNumber(), planeData.getPlaneModelData());    }

    @Override
    public RouteData add(RouteData routeData) {

        // Create dummy Data object.
        return new RouteData(routeData.getOrigin(), routeData.getDestination(), routeData.getDistance());
    }

    @Override
    public FlightData add(FlightData flightData) {
        return new FlightData(flightData.getOrigin(), flightData.getDestination(),flightData.getDeparture(),flightData.getArrival());
    }

    @Override
    public List<AirportData> getAllAirports() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List<PlaneData> getAllPlanes() {
        throw new UnsupportedOperationException("Not supported yet.");    }

    @Override
    public List<RouteData> getAllRoutes() {
        throw new UnsupportedOperationException("Not supported yet.");    }

    @Override
    public List<FlightData> getAllFlights() {
        throw new UnsupportedOperationException("Not supported yet.");    }
}
