package persistence;

import datarecords.*;

import java.net.PasswordAuthentication;
import java.util.List;

/**
 * This class knows everything about storing and retrieving data from
 * the database. At the moment only returns dummy object with an id that is set.
 * Normally it will connect to a database and do all the handling.
 *
 * @author Jannick Gruschka
 */
public class StorageServiceImpl implements StorageService{


    DatabaseManager databaseManager = new DatabaseManagerImpl();


    @Override
    public AirportData add(AirportData airportData) throws Exception {

        databaseManager.executeSQLInsert(databaseManager.prepareAirportInsert(airportData));
        // Create dummy Data object with id. Normally, the id would be generated by the database
        return new AirportData(airportData.getAirportName(), airportData.getAbbreviation(), airportData.getCountryName(), airportData.getCoordinateData());

    }

    @Override
    public PlaneData add(PlaneData planeData) throws Exception {

        databaseManager.executeSQLInsert(databaseManager.preparePlaneInsert(planeData));
        // Create dummy Data object.
        return new PlaneData(planeData.getPlaneNumber(), planeData.getPlaneModelData());    }

    @Override
    public RouteData add(RouteData routeData) {

        // Create dummy Data object.
        return new RouteData(routeData.getOrigin(), routeData.getDestination(), routeData.getDistance());
    }

    @Override
    public FlightData add(FlightData flightData) {
        return new FlightData(flightData.getRoute(),flightData.getDeparture(),flightData.getArrival(),flightData.getPlane(), flightData.getPrice(), flightData.getEconomy(), flightData.getBusiness(), flightData.getFirstClass());
    }

    @Override
    public boolean add(AccountData accountData) throws Exception{
        return databaseManager.executeSQLInsert(databaseManager.prepareAccountInsert(accountData));
    }

    @Override
    public PasswordAuthentication getAccountData(PasswordAuthentication passwordAuthentication) throws Exception {
        return databaseManager.getAccountData(passwordAuthentication.getUserName());
    }

    @Override
    public String getSalt(String str) throws Exception {
        return databaseManager.getSalt(str);
    }

    @Override
    public List<AirportData> getAllAirports() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List<PlaneData> getAllPlanes() {
        throw new UnsupportedOperationException("Not supported yet.");    }

    @Override
    public List<RouteData> getAllRoutes() {
        throw new UnsupportedOperationException("Not supported yet.");    }

    @Override
    public List<FlightData> getAllFlights() {
        throw new UnsupportedOperationException("Not supported yet.");    }
}
