package persistence;

import datarecords.AirportData;
import java.util.List;

/**
 * This class knows everything about storing and retrieving customers from
 * the database. At the moment only returns dummy object with an id that is set.
 * Normally it will connect to a database and do all the handling.
 * 
 * @author Informatics Fontys Venlo
 */
class AirportStorageServiceImpl implements AirportStorageService {

    @Override
    public AirportData add(AirportData airportData) {
        
        // Create dummy customerData object with id. Normally, the id would be generated by the database
        return new AirportData( 1, airportData.getAirportName(), airportData.getAbbreviation(), airportData.getCityName(), airportData.getCountryName());
        
    }

    @Override
    public List<AirportData> getAll() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
}
